# basic
#
title: life as a hippie hacker
subtitle: patterns of consciousness in a sea of matter
favicon: http://dinosaur.is/favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: /images/avatar.jpg
banner_small: /images/cover0.jpg
banner_large: /images/cover0.jpg

# disqus
# disqus_shortname: ahdinosaur

# social
social:
  github: https://github.com/ahdinosaur
  twitter: https://twitter.com/ahdinosaur
  #  weibo: http://weibo.com/cha12chalyc

# nav #
nav:
  home: .
  archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


  # google_analytics: # Put tracking ID here
